/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ufrpe.prog2.sistemaconsulta1.gui;

import javax.swing.*;

/**
 *
 * @author nini
 */
public class MenuInicial extends javax.swing.JFrame {

    /**
     * Creates new form MenuInicial
     */
    public MenuInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCadastrarMedicoMenu = new javax.swing.JButton();
        jButtonCadastrarPacienteMenu = new javax.swing.JButton();
        jButtonCadastrarAgendamentoMenu = new javax.swing.JButton();
        jButtonListarMedicosMenu = new javax.swing.JButton();
        jButtonListarPacientesMenu = new javax.swing.JButton();
        jButtonListarAgendamentosMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonCadastrarMedicoMenu.setText("Cadastrar Médico");
        jButtonCadastrarMedicoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarMedicoMenuActionPerformed(evt);
            }
        });

        jButtonCadastrarPacienteMenu.setText("Cadastrar Paciente");
        jButtonCadastrarPacienteMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarPacienteMenuActionPerformed(evt);
            }
        });

        jButtonCadastrarAgendamentoMenu.setText("Cadastrar Agendamento");
        jButtonCadastrarAgendamentoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarAgendamentoMenuActionPerformed(evt);
            }
        });

        jButtonListarMedicosMenu.setText("Listar Médicos");
        jButtonListarMedicosMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarMedicosMenuActionPerformed(evt);
            }
        });

        jButtonListarPacientesMenu.setText("Listar Pacientes");
        jButtonListarPacientesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarPacientesMenuActionPerformed(evt);
            }
        });

        jButtonListarAgendamentosMenu.setText("Listar Agendamentos");
        jButtonListarAgendamentosMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarAgendamentosMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCadastrarPacienteMenu)
                    .addComponent(jButtonCadastrarMedicoMenu)
                    .addComponent(jButtonCadastrarAgendamentoMenu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonListarMedicosMenu, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonListarPacientesMenu, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonListarAgendamentosMenu, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastrarMedicoMenu)
                    .addComponent(jButtonListarMedicosMenu))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastrarPacienteMenu)
                    .addComponent(jButtonListarPacientesMenu))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastrarAgendamentoMenu)
                    .addComponent(jButtonListarAgendamentosMenu))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarMedicoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarMedicoMenuActionPerformed
        // TODO add your handling code here:
        GUICadastroMedico guiMedico = new GUICadastroMedico();
            guiMedico.setVisible(true);
            guiMedico.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButtonCadastrarMedicoMenuActionPerformed

    private void jButtonListarMedicosMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarMedicosMenuActionPerformed
        // TODO add your handling code here:
            GUIListaMedicos guiListaMedicos = new GUIListaMedicos();
            guiListaMedicos.setVisible(true);
            guiListaMedicos.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButtonListarMedicosMenuActionPerformed

    private void jButtonCadastrarAgendamentoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarAgendamentoMenuActionPerformed
        // TODO add your handling code here:
        GUICadastroAgendamento guiAgendamento = new GUICadastroAgendamento();
        guiAgendamento.setVisible(true);
        guiAgendamento.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButtonCadastrarAgendamentoMenuActionPerformed

    private void jButtonCadastrarPacienteMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarPacienteMenuActionPerformed
        // TODO add your handling code here:
        GUICadastroPaciente guiPaciente = new GUICadastroPaciente();
        guiPaciente.setVisible(true);
        guiPaciente.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButtonCadastrarPacienteMenuActionPerformed

    private void jButtonListarPacientesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarPacientesMenuActionPerformed
        // TODO add your handling code here:
        GUIListaPacientes guiListaPacientes = new GUIListaPacientes();
        guiListaPacientes.setVisible(true);
        guiListaPacientes.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButtonListarPacientesMenuActionPerformed

    private void jButtonListarAgendamentosMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarAgendamentosMenuActionPerformed
        // TODO add your handling code here:
        GUIListaAgendamentos guiListaAgendamentos = new GUIListaAgendamentos();
        guiListaAgendamentos.setVisible(true);
        guiListaAgendamentos.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButtonListarAgendamentosMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrarAgendamentoMenu;
    private javax.swing.JButton jButtonCadastrarMedicoMenu;
    private javax.swing.JButton jButtonCadastrarPacienteMenu;
    private javax.swing.JButton jButtonListarAgendamentosMenu;
    private javax.swing.JButton jButtonListarMedicosMenu;
    private javax.swing.JButton jButtonListarPacientesMenu;
    // End of variables declaration//GEN-END:variables
}
